optimizer_params:
  lr: 0.0001
optimizer: Adam
criterion: VAE_LOSS
cluster_params:
  n_clusters: 17
exp_file: vae_kmeans_no_class_balance_no_augmentation_naive.pt
exp_params:
  naive: True
epochs: 2000
